name: dwmpr
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  http: any

  font_awesome_flutter: any
  bidirectional_scroll_view:
    git: https://github.com/mono0926/flutter-bidirectional_scrollview_plugin.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/RobotoMono-Medium.ttf
